In [1]:
import random
import datetime
import pandas as pd
import pyodbc

In [31]:
pd.set_option('display.max_columns',21)

In [2]:
# Connect to the database
connection_string = "Driver={ODBC Driver 17 for SQL Server};Server=LOFTY360x\SQLEXPRESS;Database=LOFTY VENTURES ;Trusted_Connection=yes;"
conn = pyodbc.connect(connection_string)
cursor = conn.cursor()

Populating the Product_Table

In [6]:
# Generate sample data
product_names = ['Product A', 'Product B', 'Product C', 'Product D', 'Product E', 'Product F', 'Product G', 'Product H', 'Product I', 'Product J', 'Product K', 'Product L', 'Product M', 'Product N', 'Product O', 'Product P', 'Product Q', 'Product R', 'Product S', 'Product T', 'Product U', 'Product V', 'Product W', 'Product X']
categories = ['Utilities', 'Provisions', 'Tools', 'Miscellaneous']
vendorID = [1, 2, 3, 4, 5, 6, 7]

# Generate and insert data
for i in range(24):
    product_name = random.choice(product_names)
    category = random.choice(categories)
    cost_price = random.uniform(5.0, 50.0)
    selling_price = cost_price * random.uniform(1.2, 1.5)
    vendor = random.choice(vendorID)
    stock_quantity = random.randint(50, 200)

    # Insert data into the database
    cursor.execute(f"INSERT INTO PRODUCT_TABLE (Product_name, Category, Cost_Price, Selling_Price, VendorID, Quantity_in_stock) VALUES (?, ?, ?, ?, ?, ?)",
                   product_name, category, round(cost_price,2), round(selling_price,2), vendor, stock_quantity)

    # Commit the transaction
    conn.commit()

Populating the sales table

In [11]:
# Define the time period (1 month)
start_date = datetime.date(2023, 8, 1)
end_date = datetime.date(2023, 8, 31)

# Generate and insert sales data for each day
current_date = start_date
sales_data = []

while current_date <= end_date:
    product_id = random.randint(102, 125)  
    quantity_sold = random.randint(1, 20)
    sale_date = current_date
    revenue = round(random.uniform(50.0, 300.0),2)

    data = {'ProductID' : product_id,
            'Sale_Date' :  sale_date,
             'Quantity_sold' : quantity_sold,
             'Revenue' : revenue }
    
    sales_data.append(data)

    current_date += datetime.timedelta(days=1)

In [15]:
data_df = pd.DataFrame(sales_data)
data_df

    ProductID   Sale_Date  Quantity_sold  Revenue
0       113.0  2023-08-01            5.0   265.30
1       117.0  2023-08-02            8.0   284.80
2       104.0  2023-08-03           19.0    83.78
3       121.0  2023-08-04            2.0   146.80
4       107.0  2023-08-05           12.0   255.89
5       117.0  2023-08-06            4.0   200.76
6       109.0  2023-08-07           11.0   232.86
7       106.0  2023-08-08            1.0   122.52
8       109.0  2023-08-09            6.0   290.11
9       116.0  2023-08-10            9.0   221.55
10      109.0  2023-08-11           14.0   285.55
11      114.0  2023-08-12           17.0   208.58
12      118.0  2023-08-13           19.0    82.87
13      118.0  2023-08-14            3.0   254.00
14      108.0  2023-08-15            5.0   254.75
15      121.0  2023-08-16            6.0   168.70
16      122.0  2023-08-17           10.0    94.76
17      110.0  2023-08-18           15.0   172.46
18      109.0  2023-08-19            2.0   208.00
19      102.0  2023-08-20           12.0   186.15
20      116.0  2023-08-21           19.0    92.46
21      124.0  2023-08-22            3.0    52.38
22      116.0  2023-08-23           14.0   234.74
23      122.0  2023-08-24            3.0    96.09
24      107.0  2023-08-25           14.0    79.97
25      107.0  2023-08-26           16.0   245.23
26      108.0  2023-08-27            3.0   122.63
27      114.0  2023-08-28            1.0   212.45
28      112.0  2023-08-29            6.0   207.84
29      116.0  2023-08-30           19.0   239.00
30      117.0  2023-08-31           14.0   222.86

In [14]:
for index, row in data_df.iterrows():
    query = """
    INSERT INTO SALES_TABLE (ProductID, Sale_Date, Quantity_sold, Revenue)
    VALUES (?, ?, ?, ?)
    """
    cursor.execute(query, row['ProductID'], row['Sale_Date'], row['Quantity_sold'], row['Revenue'])
    
conn.commit()
cursor.close()
conn.close()

Populating the inventory table

In [14]:
# Define the time period (1 month)
start_date = datetime.date(2023, 8, 1)
end_date = datetime.date(2023, 8, 31)

# Generate and insert inventory data for each day
current_date = start_date
invent_list = []
product_name_mapping = {102:	'Product P',
                        103:	'Product X',
                        104:	'Product C',
                        105:	'Product L',
                        106:	'Product L',
                        107:	'Product W',
                        108:	'Product S',
                        109:	'Product T',
                        110:	'Product K',
                        111:	'Product F',
                        112:	'Product M',
                        113:	'Product A',
                        114:	'Product P',
                        115:	'Product R',
                        116:	'Product E',
                        117:	'Product J',
                        118:	'Product S',
                        119:	'Product K',
                        120:	'Product Q',
                        121:	'Product N',
                        122:	'Product E',
                        123:	'Product U',
                        124:	'Product A',
                        125:	'Product H'}

while current_date <= end_date:
    product_id = random.randint(102, 125)
    product_name = product_name_mapping.get(product_id, 'unknoproduct')
    stock_quantity = random.randint(50, 200)
    reorder_threshold = random.randint(20, 50)

    invnt_data = {'ProductID': product_id
            ,'Product_name': product_name
            ,'Stock_quantity': stock_quantity
            ,'Reorder_threshold': reorder_threshold }
    
    current_date += datetime.timedelta(days=1)
    
    invent_list.append(invnt_data)

In [26]:
invt_table = pd.DataFrame(invent_list)
invt_table

    ProductID Product_name  Stock_quantity  Reorder_threshold
0         113    Product A              80                 23
1         117    Product J             106                 47
2         105    Product L             108                 33
3         110    Product K              57                 26
4         113    Product A             196                 46
5         124    Product A              83                 34
6         113    Product A              80                 43
7         106    Product L             188                 48
8         104    Product C              70                 43
9         121    Product N              53                 29
10        105    Product L              66                 25
11        124    Product A              82                 39
12        119    Product K             117                 49
13        102    Product P              50                 41
14        112    Product M             174                 41
15        119    Product K             162                 49
16        117    Product J              88                 47
17        116    Product E             166                 48
18        113    Product A             187                 40
19        103    Product X             146                 37
20        114    Product P             197                 48
21        115    Product R              76                 45
22        125    Product H             115                 49
23        111    Product F              78                 26
24        117    Product J             172                 28
25        125    Product H              85                 47
26        112    Product M              81                 30
27        120    Product Q             184                 31
28        122    Product E             158                 21
29        114    Product P             149                 41
30        107    Product W             128                 44

In [29]:
for index, row in invt_table.iterrows():
    query = """
    INSERT INTO INVENTORY_TABLE (ProductID, Product_name, Stock_quantity, Reorder_threshold)
    VALUES (?, ?, ?, ?)
    """
    cursor.execute(query, row['ProductID'], row['Product_name'], row['Stock_quantity'], row['Reorder_threshold'])
    
conn.commit()
cursor.close()
conn.close()

Previewing the data

In [4]:
VENDOR_TABLE = pd.read_sql('select * from VENDOR_TABLE', conn)
VENDOR_TABLE

C:\Users\chide\AppData\Local\Temp\ipykernel_19516\1348077249.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  VENDOR_TABLE = pd.read_sql('select * from VENDOR_TABLE', conn)

   VendorID Vendor_name          Contact_email  Contact_phone
0         1    VENDOR 1  WWW.VENDOR1@GMAIL.COM       80600001
1         2    VENDOR 2  WWW.VENDOR2@GMAIL.COM       80600002
2         3    VENDOR 3  WWW.VENDOR3@GMAIL.COM       80600003
3         4    VENDOR 4  WWW.VENDOR4@GMAIL.COM       80600004
4         5    VENDOR 5  WWW.VENDOR5@GMAIL.COM       80600005
5         6    VENDOR 6  WWW.VENDOR6@GMAIL.COM       80600006
6         7    VENDOR 7  WWW.VENDOR7@GMAIL.COM       80600007

In [37]:
INVENTORY_TABLE = pd.read_sql('select * from INVENTORY_TABLE', conn)
INVENTORY_TABLE

C:\Users\chide\AppData\Local\Temp\ipykernel_12884\1721658311.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  INVENTORY_TABLE = pd.read_sql('select * from INVENTORY_TABLE', conn)

    InventoryID  ProductID Product_name  Stock_quantity  Reorder_threshold
0             1        113    Product A              80                 23
1             2        117    Product J             106                 47
2             3        105    Product L             108                 33
3             4        110    Product K              57                 26
4             5        113    Product A             196                 46
5             6        124    Product A              83                 34
6             7        113    Product A              80                 43
7             8        106    Product L             188                 48
8             9        104    Product C              70                 43
9            10        121    Product N              53                 29
10           11        105    Product L              66                 25
11           12        124    Product A              82                 39
12           13        119    Product K             117                 49
13           14        102    Product P              50                 41
14           15        112    Product M             174                 41
15           16        119    Product K             162                 49
16           17        117    Product J              88                 47
17           18        116    Product E             166                 48
18           19        113    Product A             187                 40
19           20        103    Product X             146                 37
20           21        114    Product P             197                 48
21           22        115    Product R              76                 45
22           23        125    Product H             115                 49
23           24        111    Product F              78                 26
24           25        117    Product J             172                 28
25           26        125    Product H              85                 47
26           27        112    Product M              81                 30
27           28        120    Product Q             184                 31
28           29        122    Product E             158                 21
29           30        114    Product P             149                 41
30           31        107    Product W             128                 44

In [36]:
PRODUCT_TABLE = pd.read_sql('select * from PRODUCT_TABLE', conn)
PRODUCT_TABLE

C:\Users\chide\AppData\Local\Temp\ipykernel_12884\295160364.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  PRODUCT_TABLE = pd.read_sql('select * from PRODUCT_TABLE', conn)

,ProductID,Product_name,Category,Cost_Price,Selling_Price,VendorID,Quantity_in_stock
0,102,Product P,Tools,5.93,7.96,3,120
1,103,Product X,Tools,40.79,53.63,3,125
2,104,Product C,Miscellaneous,42.07,51.91,1,61
3,105,Product L,Provisions,49.89,63.87,2,179
4,106,Product L,Provisions,15.87,21.53,7,155
5,107,Product W,Provisions,11.99,15.75,1,173
6,108,Product S,Utilities,33.08,48.28,5,135
7,109,Product T,Tools,46.05,68.78,1,75
8,110,Product K,Tools,12.22,16.79,3,86
9,111,Product F,Tools,40.15,52.08,2,199
10,112,Product M,Utilities,35.10,49.85,2,95
11,113,Product A,Utilities,15.14,22.29,3,115
12,114,Product P,Utilities,27.18,34.73,2,122
13,115,Product R,Provisions,16.92,20.52,3,115
14,116,Product E,Utilities,23.90,29.53,7,74
15,117,Product J,Tools,10.10,12.67,5,88
16,118,Product S,Miscellaneous,45.51,59.02,1,68
17,119,Product K,Miscellaneous,15.25,19.36,7,143
18,120,Product Q,Provisions,8.88,11.31,4,145
19,121,Product N,Tools,15.92,23.68,7,172
20,122,Product E,Miscellaneous,12.82,18.86,7,189
21,123,Product U,Utilities,19.42,24.91,6,185
22,124,Product A,Miscellaneous,35.53,50.55,3,120
23,125,Product H,Utilities,45.44,55.70,4,91

In [32]:
lofty_ventures_database = pd.read_sql('''SELECT *
                                    FROM [dbo].[VENDOR_TABLE]
                                        FULL OUTER JOIN [dbo].[PRODUCT_TABLE] ON VENDOR_TABLE.VendorID = PRODUCT_TABLE.VendorID
                                        FULL OUTER JOIN [dbo].[INVENTORY_TABLE] ON PRODUCT_TABLE.ProductID = INVENTORY_TABLE.ProductID
                                        FULL OUTER JOIN [dbo].[SALES_TABLE] ON INVENTORY_TABLE.ProductID = SALES_TABLE.ProductID
                                    ORDER BY PRODUCT_TABLE.PRODUCT_NAME
                                      
                                    ''', conn)
lofty_ventures_database

C:\Users\chide\AppData\Local\Temp\ipykernel_19516\3972600369.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lofty_ventures_database = pd.read_sql('''SELECT *

,VendorID,Vendor_name,Contact_email,Contact_phone,ProductID,Product_name,Category,Cost_Price,Selling_Price,Quantity_in_stock,InventoryID,Stock_quantity,Reorder_threshold,SaleID,Sale_Date,Quantity_sold,Revenue
0,NaN,None,None,NaN,109.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,7.0,2023-08-07,11.0,232.86
1,NaN,None,None,NaN,109.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2023-08-09,6.0,290.11
2,NaN,None,None,NaN,109.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,11.0,2023-08-11,14.0,285.55
3,NaN,None,None,NaN,109.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,19.0,2023-08-19,2.0,208.00
4,NaN,None,None,NaN,118.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2023-08-13,19.0,82.87
5,NaN,None,None,NaN,118.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,14.0,2023-08-14,3.0,254.00
6,NaN,None,None,NaN,108.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,15.0,2023-08-15,5.0,254.75
7,NaN,None,None,NaN,108.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,27.0,2023-08-27,3.0,122.63
8,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,113.0,Product A,Utilities,15.14,22.29,115.0,1.0,80.0,23.0,1.0,2023-08-01,5.0,265.30
9,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,113.0,Product A,Utilities,15.14,22.29,115.0,5.0,196.0,46.0,1.0,2023-08-01,5.0,265.30
10,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,113.0,Product A,Utilities,15.14,22.29,115.0,7.0,80.0,43.0,1.0,2023-08-01,5.0,265.30
11,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,113.0,Product A,Utilities,15.14,22.29,115.0,19.0,187.0,40.0,1.0,2023-08-01,5.0,265.30
12,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,116.0,Product B,Utilities,23.90,29.53,74.0,18.0,166.0,48.0,10.0,2023-08-10,9.0,221.55
13,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,116.0,Product B,Utilities,23.90,29.53,74.0,18.0,166.0,48.0,21.0,2023-08-21,19.0,92.46
14,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,116.0,Product B,Utilities,23.90,29.53,74.0,18.0,166.0,48.0,23.0,2023-08-23,14.0,234.74
15,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,116.0,Product B,Utilities,23.90,29.53,74.0,18.0,166.0,48.0,30.0,2023-08-30,19.0,239.00
16,1.0,VENDOR 1,WWW.VENDOR1@GMAIL.COM,80600001.0,104.0,Product C,Miscellaneous,42.07,51.91,61.0,9.0,70.0,43.0,3.0,2023-08-03,19.0,83.78
17,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,124.0,Product D,Miscellaneous,35.53,50.55,120.0,6.0,83.0,34.0,22.0,2023-08-22,3.0,52.38
18,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,124.0,Product D,Miscellaneous,35.53,50.55,120.0,12.0,82.0,39.0,22.0,2023-08-22,3.0,52.38
19,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,122.0,Product E,Miscellaneous,12.82,18.86,189.0,29.0,158.0,21.0,17.0,2023-08-17,10.0,94.76
20,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,122.0,Product E,Miscellaneous,12.82,18.86,189.0,29.0,158.0,21.0,24.0,2023-08-24,3.0,96.09
21,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,NaN,Product F,Tools,40.15,52.08,199.0,24.0,78.0,26.0,NaN,None,NaN,NaN
22,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,NaN,Product G,Miscellaneous,15.25,19.36,143.0,13.0,117.0,49.0,NaN,None,NaN,NaN
23,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,NaN,Product G,Miscellaneous,15.25,19.36,143.0,16.0,162.0,49.0,NaN,None,NaN,NaN
24,4.0,VENDOR 4,WWW.VENDOR4@GMAIL.COM,80600004.0,NaN,Product H,Utilities,45.44,55.70,91.0,23.0,115.0,49.0,NaN,None,NaN,NaN
25,4.0,VENDOR 4,WWW.VENDOR4@GMAIL.COM,80600004.0,NaN,Product H,Utilities,45.44,55.70,91.0,26.0,85.0,47.0,NaN,None,NaN,NaN
26,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,NaN,Product I,Provisions,49.89,63.87,179.0,3.0,108.0,33.0,NaN,None,NaN,NaN
27,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,NaN,Product I,Provisions,49.89,63.87,179.0,11.0,66.0,25.0,NaN,None,NaN,NaN
28,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,2.0,106.0,47.0,2.0,2023-08-02,8.0,284.80
29,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,2.0,106.0,47.0,6.0,2023-08-06,4.0,200.76
30,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,2.0,106.0,47.0,31.0,2023-08-31,14.0,222.86
31,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,17.0,88.0,47.0,2.0,2023-08-02,8.0,284.80
32,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,17.0,88.0,47.0,6.0,2023-08-06,4.0,200.76
33,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,17.0,88.0,47.0,31.0,2023-08-31,14.0,222.86
34,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,25.0,172.0,28.0,2.0,2023-08-02,8.0,284.80
35,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,25.0,172.0,28.0,6.0,2023-08-06,4.0,200.76
36,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,117.0,Product J,Tools,10.10,12.67,88.0,25.0,172.0,28.0,31.0,2023-08-31,14.0,222.86
37,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,110.0,Product K,Tools,12.22,16.79,86.0,4.0,57.0,26.0,18.0,2023-08-18,15.0,172.46
38,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,106.0,Product L,Provisions,15.87,21.53,155.0,8.0,188.0,48.0,8.0,2023-08-08,1.0,122.52
39,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,112.0,Product M,Utilities,35.10,49.85,95.0,15.0,174.0,41.0,29.0,2023-08-29,6.0,207.84
40,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,112.0,Product M,Utilities,35.10,49.85,95.0,27.0,81.0,30.0,29.0,2023-08-29,6.0,207.84
41,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,121.0,Product N,Tools,15.92,23.68,172.0,10.0,53.0,29.0,4.0,2023-08-04,2.0,146.80
42,7.0,VENDOR 7,WWW.VENDOR7@GMAIL.COM,80600007.0,121.0,Product N,Tools,15.92,23.68,172.0,10.0,53.0,29.0,16.0,2023-08-16,6.0,168.70
43,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,114.0,Product O,Utilities,27.18,34.73,122.0,21.0,197.0,48.0,12.0,2023-08-12,17.0,208.58
44,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,114.0,Product O,Utilities,27.18,34.73,122.0,21.0,197.0,48.0,28.0,2023-08-28,1.0,212.45
45,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,114.0,Product O,Utilities,27.18,34.73,122.0,30.0,149.0,41.0,12.0,2023-08-12,17.0,208.58
46,2.0,VENDOR 2,WWW.VENDOR2@GMAIL.COM,80600002.0,114.0,Product O,Utilities,27.18,34.73,122.0,30.0,149.0,41.0,28.0,2023-08-28,1.0,212.45
47,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,102.0,Product P,Tools,5.93,7.96,120.0,14.0,50.0,41.0,20.0,2023-08-20,12.0,186.15
48,4.0,VENDOR 4,WWW.VENDOR4@GMAIL.COM,80600004.0,NaN,Product Q,Provisions,8.88,11.31,145.0,28.0,184.0,31.0,NaN,None,NaN,NaN
49,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,NaN,Product R,Provisions,16.92,20.52,115.0,22.0,76.0,45.0,NaN,None,NaN,NaN
50,1.0,VENDOR 1,WWW.VENDOR1@GMAIL.COM,80600001.0,NaN,None,Miscellaneous,45.51,59.02,68.0,NaN,NaN,NaN,NaN,None,NaN,NaN
51,1.0,VENDOR 1,WWW.VENDOR1@GMAIL.COM,80600001.0,NaN,None,Tools,46.05,68.78,75.0,NaN,NaN,NaN,NaN,None,NaN,NaN
52,6.0,VENDOR 6,WWW.VENDOR6@GMAIL.COM,80600006.0,NaN,None,Utilities,19.42,24.91,185.0,NaN,NaN,NaN,NaN,None,NaN,NaN
53,5.0,VENDOR 5,WWW.VENDOR5@GMAIL.COM,80600005.0,NaN,None,Utilities,33.08,48.28,135.0,NaN,NaN,NaN,NaN,None,NaN,NaN
54,1.0,VENDOR 1,WWW.VENDOR1@GMAIL.COM,80600001.0,107.0,Product W,Provisions,11.99,15.75,173.0,31.0,128.0,44.0,5.0,2023-08-05,12.0,255.89
55,1.0,VENDOR 1,WWW.VENDOR1@GMAIL.COM,80600001.0,107.0,Product W,Provisions,11.99,15.75,173.0,31.0,128.0,44.0,25.0,2023-08-25,14.0,79.97
56,1.0,VENDOR 1,WWW.VENDOR1@GMAIL.COM,80600001.0,107.0,Product W,Provisions,11.99,15.75,173.0,31.0,128.0,44.0,26.0,2023-08-26,16.0,245.23
57,3.0,VENDOR 3,WWW.VENDOR3@GMAIL.COM,80600003.0,NaN,Product X,Tools,40.79,53.63,125.0,20.0,146.0,37.0,NaN,None,NaN,NaN